version: '3.8'

services:
  greenlight:
    build:
      context: .
      dockerfile: dockerfile
    container_name: greenlight_api
    ports:
      - "8087:4000"
    env_file:
      - .env
    volumes:
      - .:/app


